### PR TITLE
Update audiotube to v23.01.0

### PR DESCRIPTION
**Pull request by NeroBurner**
Just saw the announcement and installed the flatpak. I really like v22.10, but I'd really like to have the latest release. Happy this is FOSS, so I can help :)

### CODE REVIEW

**Comment by NeroBurner** [comment]
@JBBgameich please review

**Comment by JBBgameich** [comment]
Thank you, the changes look good so far.

Just one little thing missing:
Can you please run `./update-generated-sources.sh v23.01.0`  to sync the python packages with the versions that are used in the nightly flatpak?

**Comment by NeroBurner** [comment]
sure :+1: 
pushed the updated commit

**Pull request merged**
